config/routes.rb
Archives::Application.routes.draw do

  devise_for :users

  resources :collections do
    resources :collections
    resources :albums do
      resources :items
    end
  end
  resources :albums
  resources :items
  resources :comments

  root :to => 'collections#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :city, :collection_id, :contact_person, :country, :is_event, :name, :state, :venue, :when, :user_id
  
  belongs_to :collection
  has_many :collections
  has_many :albums
  
  acts_as_tree
  
  validates_presence_of :name
  validates_length_of :contact_person, :maximum => 255, :message => "255 characters max, please."
  validates_presence_of :when, :city, :state, :country, :if => Proc.new { |collection| collection.is_event }
  
  def self.collections_for_select
    collections = Collection.all
    collections.unshift Collection.new({:id => 0, :name => "None"})
  end
  
  def formatted_location
    location = [self.city, self.state, self.country]
    location.reject! { |piece| piece.nil? || piece.blank? }
    municipalities = location.join(", ")
    
    municipalities = "At #{self.venue} in #{municipalities}" unless self.venue || self.venue.nil? || self.venue.blank?
    municipalities = "In #{municipalities}" if (self.venue.nil? || self.venue.blank?) && !municipalities.empty?
    
    municipalities
  end
  
  def self.all_root_collections
    self.where( :collection_id => nil )
  end
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all_root_collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(params[:collection])

    @collection.user_id = current_user.id

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.text_field :when %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :collection_id %><br />
    <%= f.collection_select :collection_id, Collection.collections_for_select, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :is_event %><br />
    <%= f.check_box :is_event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>All Collections</h1>

<% @collections.each do |collection| %>
<ul>
    <li><%= link_to collection.name, collection %><br /><%= collection.when %></li>
</ul>
<% end %>

<br />

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p>
  <h2><%= @collection.name %></h2><span class="when"><%= @collection.when %></span>
  <p>
      <%= @collection.formatted_location unless @collection.formatted_location.blank? %>
  </p>
  
</p>

<% unless @collection.contact_person.empty? %>
<p>
  <b>Contacts:</b>
  <%= @collection.contact_person %>
</p>
<% end %>

<% unless @collection.collection.nil? %>
<p>
  <b>Parent Collection:</b>
  <%= if @collection.collection then link_to @collection.collection.name, @collection.collection else "None" end %>
</p>
<% end %>

<p>
    <b>Actions:</b>
    <ul>
        <li><%= link_to 'New Album', new_collection_album_path(@collection) %></li>
        <li><%= link_to 'New Collection', new_collection_collection_path(@collection) %></li>
        <li><%= link_to 'Edit', edit_collection_path(@collection) %></li>
        <li><%= link_to 'Back', collections_path %></li>
    </ul>
</p>

<p>
  <b>Event?:</b>
  <%= @collection.is_event %>
</p>

<div id="child_collections">
    <header>
        <h3>Collections:</h3>
    </header>
    <% @collection.collections.each do |collection| %>
    <p><%= link_to collection.name, collection %></p>
    <% end %>
    <%= "No collections." if @collection.collections.nil? || @collection.collections.empty? %>
</div>

<div id="child_albums">
    <header>
        <h3>Albums:</h3>
    </header>
    <% @collection.albums.each do |album| %>
    <p><%= link_to album.name, album %></p>
    <% end %>
    <%= "No albums." if @collection.albums.nil? || @collection.albums.empty? %>
</div>